# Generated by Django 3.0.6 on 2021-09-10 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CommunicationAct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conversation_id', models.CharField(default='0', max_length=200, verbose_name='Conversation ID')),
                ('type', models.CharField(choices=[('r_c', 'reqest conversation'), ('r_c_a', 'reqest conversation answer'), ('r_m_q', 'request make queries'), ('r_m_q_a', 'request make queries answer'), ('r_r_q', 'request ready queries'), ('q_r_i', 'queries ready info'), ('q_s', 'set of queries'), ('r_q_e', 'requesr queries execution'), ('r_q_e_a', 'requesr queries execution answer'), ('q_e_i', 'queries executed info'), ('r_q_r', 'requesr queries result'), ('q_r', 'queries result'), ('r_u', 'reqest unsubscribe'), ('r_u_a', 'reqest unsubscribe ansver')], default='r_m_q', max_length=10, verbose_name='Messege type')),
                ('content', models.TextField(blank=True, null=True, verbose_name='Messege content')),
                ('query_sqrvice_id', models.CharField(blank=True, max_length=200, null=True, verbose_name='ID by query creation service')),
                ('ontology_sqrvice_id', models.CharField(blank=True, max_length=200, null=True, verbose_name='ID by query ontology service')),
                ('receivers', models.TextField(default='self', verbose_name='Receivers')),
                ('date_time', models.DateTimeField(auto_now_add=True, verbose_name='Time')),
            ],
            options={
                'verbose_name': 'Communication Acts',
                'db_table': 'CommunicationActs',
            },
        ),
        migrations.CreateModel(
            name='UserDialogPosition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conversation_id', models.CharField(default='0', max_length=200, verbose_name='Conversation ID')),
                ('type', models.CharField(choices=[('question', 'question'), ('answer', 'answer'), ('additional_answer', 'additional answer'), ('result_evaluation', 'result evaluation')], default='question', max_length=30, verbose_name='Messege type')),
                ('content', models.TextField(blank=True, null=True, verbose_name='Messege content')),
                ('additional_info', models.TextField(blank=True, null=True, verbose_name='Additional information')),
                ('date_time', models.DateTimeField(auto_now_add=True, verbose_name='Time')),
            ],
            options={
                'verbose_name': 'Dialog messages',
                'db_table': 'DialogPositions',
            },
        ),
    ]
